/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package unisystems.gui;

import java.awt.BorderLayout;
import java.awt.Component;
import java.util.regex.Matcher;
import java.util.regex.Pattern;
import javax.swing.DefaultComboBoxModel;
import javax.swing.JOptionPane;
import javax.swing.JPanel;
import unisystems.Administrator;
import unisystems.Staff;
import unisystems.UniSystems;
import unisystems.VehicleAccessGroup;


/**
 * @author Joseph Kellaway, Alex Murphy and Zakaria Robinson
 * Creates the administrator java dialog and populates the list within
 * Also creates a link to the parent JFHome
 */
public class JDAdministrator extends javax.swing.JDialog {
    private Integer iD;
    private JFHome parent;
    private DefaultComboBoxModel<VehicleAccessGroup> model =
            new DefaultComboBoxModel<>(VehicleAccessGroup.values());
    
    /**
     * Creates new form AddAdministrater
     */
    public JDAdministrator(java.awt.Frame parent, boolean modal) {
        super(parent, modal);
        initComponents();
    }
    
    /**
     * @param parent. This is the parent frame JFHome
     */
    public void setParent(JFHome parent) {
        this.parent = parent;
    }
    
    /**
     * @param panel. A string that determines which panel to add
     * Case statement that determines which panel to display
     */
    public void setPanel(String panel){
        switch (panel){
            case "add":
                changePanel(pnlAddAdministrator);
                break;
            case "edit":
                changePanel(pnlEditAdministrator);
                break;
            case "delete":
                changePanel(pnlDeleteAdministrator);
                break;
        }
    }
    
    /**
     * @param panel The panel to be displayed
     * Removes panels then displays the new panel
     */
    private void changePanel(JPanel panel) {
        getContentPane().removeAll();
        getContentPane().add(panel, BorderLayout.CENTER);
        getContentPane().doLayout();
        update(getGraphics());
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        pnlAddAdministrator = new javax.swing.JPanel();
        txtAddName = new javax.swing.JTextField();
        jScrollPane1 = new javax.swing.JScrollPane();
        txtAddAddress = new javax.swing.JTextArea();
        cmbAddVehicleAccessGroup = new javax.swing.JComboBox();
        btnAddAdministrator = new javax.swing.JButton();
        btnCancelAdd = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        txtAddPassword = new javax.swing.JTextField();
        pnlEditAdministrator = new javax.swing.JPanel();
        jLabel5 = new javax.swing.JLabel();
        jScrollPane2 = new javax.swing.JScrollPane();
        txtEditAddress = new javax.swing.JTextArea();
        cmbEditVehicleAccessGroup = new javax.swing.JComboBox();
        btnSaveEdit = new javax.swing.JButton();
        btnCancelEdit = new javax.swing.JButton();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        txtEditName = new javax.swing.JTextField();
        txtEditPassword = new javax.swing.JTextField();
        jLabel11 = new javax.swing.JLabel();
        pnlDeleteAdministrator = new javax.swing.JPanel();
        jLabel6 = new javax.swing.JLabel();
        jLabel24 = new javax.swing.JLabel();
        lblName = new javax.swing.JLabel();
        jLabel23 = new javax.swing.JLabel();
        lblAddress = new javax.swing.JLabel();
        jLabel22 = new javax.swing.JLabel();
        lblVehicleAccessGroup = new javax.swing.JLabel();
        btnCancelDelete = new javax.swing.JButton();
        btnDeleteAdministrator = new javax.swing.JButton();
        jLabel12 = new javax.swing.JLabel();
        lblPassword = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setMaximumSize(new java.awt.Dimension(450, 450));
        setMinimumSize(new java.awt.Dimension(450, 450));
        setPreferredSize(new java.awt.Dimension(450, 450));
        setResizable(false);
        setSize(new java.awt.Dimension(450, 450));

        pnlAddAdministrator.setMaximumSize(new java.awt.Dimension(400, 450));
        pnlAddAdministrator.setMinimumSize(new java.awt.Dimension(400, 450));
        pnlAddAdministrator.setPreferredSize(new java.awt.Dimension(400, 450));

        txtAddAddress.setColumns(20);
        txtAddAddress.setRows(5);
        jScrollPane1.setViewportView(txtAddAddress);

        cmbAddVehicleAccessGroup.setModel(model);

        btnAddAdministrator.setText("Save");
        btnAddAdministrator.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAddAdministratorActionPerformed(evt);
            }
        });

        btnCancelAdd.setText("Cancel");
        btnCancelAdd.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCancelAddActionPerformed(evt);
            }
        });

        jLabel1.setText("ADD ADMINISTRATOR");

        jLabel2.setText("Name:");

        jLabel3.setText("Address:");

        jLabel4.setText("Vehicle Access Group:");

        jLabel10.setText("Password:");

        javax.swing.GroupLayout pnlAddAdministratorLayout = new javax.swing.GroupLayout(pnlAddAdministrator);
        pnlAddAdministrator.setLayout(pnlAddAdministratorLayout);
        pnlAddAdministratorLayout.setHorizontalGroup(
            pnlAddAdministratorLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlAddAdministratorLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(pnlAddAdministratorLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(pnlAddAdministratorLayout.createSequentialGroup()
                        .addComponent(btnAddAdministrator, javax.swing.GroupLayout.PREFERRED_SIZE, 125, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(btnCancelAdd, javax.swing.GroupLayout.PREFERRED_SIZE, 125, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addContainerGap())
                    .addGroup(pnlAddAdministratorLayout.createSequentialGroup()
                        .addGroup(pnlAddAdministratorLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel2)
                            .addComponent(jLabel3))
                        .addGap(209, 347, Short.MAX_VALUE))))
            .addGroup(pnlAddAdministratorLayout.createSequentialGroup()
                .addGroup(pnlAddAdministratorLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel1)
                    .addGroup(pnlAddAdministratorLayout.createSequentialGroup()
                        .addContainerGap()
                        .addGroup(pnlAddAdministratorLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel4)
                            .addComponent(jLabel10))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(pnlAddAdministratorLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(jScrollPane1)
                            .addComponent(txtAddName, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(txtAddPassword, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(cmbAddVehicleAccessGroup, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))))
                .addGap(0, 0, Short.MAX_VALUE))
        );
        pnlAddAdministratorLayout.setVerticalGroup(
            pnlAddAdministratorLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, pnlAddAdministratorLayout.createSequentialGroup()
                .addComponent(jLabel1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(pnlAddAdministratorLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(txtAddName, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(25, 25, 25)
                .addGroup(pnlAddAdministratorLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel3)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(pnlAddAdministratorLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel4)
                    .addComponent(cmbAddVehicleAccessGroup, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(pnlAddAdministratorLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel10)
                    .addComponent(txtAddPassword, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(73, 73, 73)
                .addGroup(pnlAddAdministratorLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnAddAdministrator, javax.swing.GroupLayout.PREFERRED_SIZE, 45, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnCancelAdd, javax.swing.GroupLayout.PREFERRED_SIZE, 45, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(90, Short.MAX_VALUE))
        );

        pnlEditAdministrator.setMaximumSize(new java.awt.Dimension(450, 450));
        pnlEditAdministrator.setMinimumSize(new java.awt.Dimension(450, 450));
        pnlEditAdministrator.setPreferredSize(new java.awt.Dimension(450, 450));

        jLabel5.setText("EDIT ADMINISTRATOR");

        txtEditAddress.setColumns(20);
        txtEditAddress.setRows(5);
        jScrollPane2.setViewportView(txtEditAddress);

        cmbEditVehicleAccessGroup.setModel(model);

        btnSaveEdit.setText("Save");
        btnSaveEdit.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSaveEditActionPerformed(evt);
            }
        });

        btnCancelEdit.setText("Cancel");
        btnCancelEdit.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCancelEditActionPerformed(evt);
            }
        });

        jLabel7.setText("Name:");

        jLabel8.setText("Address:");

        jLabel9.setText("Vehicle Access Group:");

        jLabel11.setText("Password:");

        javax.swing.GroupLayout pnlEditAdministratorLayout = new javax.swing.GroupLayout(pnlEditAdministrator);
        pnlEditAdministrator.setLayout(pnlEditAdministratorLayout);
        pnlEditAdministratorLayout.setHorizontalGroup(
            pnlEditAdministratorLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlEditAdministratorLayout.createSequentialGroup()
                .addComponent(jLabel5)
                .addGap(0, 0, Short.MAX_VALUE))
            .addGroup(pnlEditAdministratorLayout.createSequentialGroup()
                .addGroup(pnlEditAdministratorLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, pnlEditAdministratorLayout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(btnSaveEdit, javax.swing.GroupLayout.PREFERRED_SIZE, 125, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(btnCancelEdit, javax.swing.GroupLayout.PREFERRED_SIZE, 125, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(pnlEditAdministratorLayout.createSequentialGroup()
                        .addGap(54, 54, 54)
                        .addGroup(pnlEditAdministratorLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(txtEditName, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addContainerGap())
            .addGroup(pnlEditAdministratorLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(pnlEditAdministratorLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(pnlEditAdministratorLayout.createSequentialGroup()
                        .addComponent(jLabel9)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(cmbEditVehicleAccessGroup, javax.swing.GroupLayout.PREFERRED_SIZE, 166, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(pnlEditAdministratorLayout.createSequentialGroup()
                        .addComponent(jLabel11)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(txtEditPassword, javax.swing.GroupLayout.PREFERRED_SIZE, 166, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(159, Short.MAX_VALUE))
            .addGroup(pnlEditAdministratorLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(pnlEditAdministratorLayout.createSequentialGroup()
                    .addGap(5, 5, 5)
                    .addGroup(pnlEditAdministratorLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addComponent(jLabel7)
                        .addComponent(jLabel8))
                    .addGap(181, 402, Short.MAX_VALUE)))
        );
        pnlEditAdministratorLayout.setVerticalGroup(
            pnlEditAdministratorLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlEditAdministratorLayout.createSequentialGroup()
                .addComponent(jLabel5)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(txtEditName, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(47, 47, 47)
                .addGroup(pnlEditAdministratorLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel9)
                    .addComponent(cmbEditVehicleAccessGroup, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(pnlEditAdministratorLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel11)
                    .addComponent(txtEditPassword, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(42, 42, 42)
                .addGroup(pnlEditAdministratorLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnCancelEdit, javax.swing.GroupLayout.PREFERRED_SIZE, 45, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnSaveEdit, javax.swing.GroupLayout.PREFERRED_SIZE, 45, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(99, Short.MAX_VALUE))
            .addGroup(pnlEditAdministratorLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(pnlEditAdministratorLayout.createSequentialGroup()
                    .addGap(30, 30, 30)
                    .addComponent(jLabel7)
                    .addGap(22, 22, 22)
                    .addComponent(jLabel8)
                    .addContainerGap(370, Short.MAX_VALUE)))
        );

        pnlDeleteAdministrator.setMaximumSize(new java.awt.Dimension(450, 450));
        pnlDeleteAdministrator.setMinimumSize(new java.awt.Dimension(450, 450));
        pnlDeleteAdministrator.setPreferredSize(new java.awt.Dimension(450, 450));

        jLabel6.setText("DELETE ADMINISTRATOR");

        jLabel24.setText("Vehicle Access Group");

        lblName.setText("lblName");

        jLabel23.setText("Address");

        lblAddress.setText("lblAddress");

        jLabel22.setText("Name");

        lblVehicleAccessGroup.setText("lblVehicleAccessGroup");

        btnCancelDelete.setText("Cancel");
        btnCancelDelete.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCancelDeleteActionPerformed(evt);
            }
        });

        btnDeleteAdministrator.setText("Delete");
        btnDeleteAdministrator.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnDeleteAdministratorActionPerformed(evt);
            }
        });

        jLabel12.setText("Password:");

        lblPassword.setText("lblPassword");

        javax.swing.GroupLayout pnlDeleteAdministratorLayout = new javax.swing.GroupLayout(pnlDeleteAdministrator);
        pnlDeleteAdministrator.setLayout(pnlDeleteAdministratorLayout);
        pnlDeleteAdministratorLayout.setHorizontalGroup(
            pnlDeleteAdministratorLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlDeleteAdministratorLayout.createSequentialGroup()
                .addComponent(jLabel6)
                .addGap(0, 0, Short.MAX_VALUE))
            .addGroup(pnlDeleteAdministratorLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(pnlDeleteAdministratorLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(pnlDeleteAdministratorLayout.createSequentialGroup()
                        .addGroup(pnlDeleteAdministratorLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel22)
                            .addComponent(jLabel23)
                            .addComponent(jLabel24)
                            .addComponent(jLabel12))
                        .addGap(66, 66, 66)
                        .addGroup(pnlDeleteAdministratorLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(lblPassword)
                            .addComponent(lblVehicleAccessGroup)
                            .addComponent(lblAddress)
                            .addComponent(lblName))
                        .addGap(0, 158, Short.MAX_VALUE))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, pnlDeleteAdministratorLayout.createSequentialGroup()
                        .addComponent(btnDeleteAdministrator, javax.swing.GroupLayout.PREFERRED_SIZE, 125, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(btnCancelDelete, javax.swing.GroupLayout.PREFERRED_SIZE, 125, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap())
        );
        pnlDeleteAdministratorLayout.setVerticalGroup(
            pnlDeleteAdministratorLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlDeleteAdministratorLayout.createSequentialGroup()
                .addComponent(jLabel6)
                .addGap(18, 18, 18)
                .addGroup(pnlDeleteAdministratorLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel22)
                    .addComponent(lblName))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(pnlDeleteAdministratorLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel23)
                    .addComponent(lblAddress))
                .addGap(18, 18, 18)
                .addGroup(pnlDeleteAdministratorLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel24)
                    .addComponent(lblVehicleAccessGroup))
                .addGap(18, 18, 18)
                .addGroup(pnlDeleteAdministratorLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel12)
                    .addComponent(lblPassword))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 191, Short.MAX_VALUE)
                .addGroup(pnlDeleteAdministratorLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnCancelDelete, javax.swing.GroupLayout.PREFERRED_SIZE, 45, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnDeleteAdministrator, javax.swing.GroupLayout.PREFERRED_SIZE, 45, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(79, 79, 79))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 400, Short.MAX_VALUE)
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(layout.createSequentialGroup()
                    .addGap(0, 0, Short.MAX_VALUE)
                    .addComponent(pnlAddAdministrator, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGap(0, 0, Short.MAX_VALUE)))
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(layout.createSequentialGroup()
                    .addContainerGap()
                    .addComponent(pnlEditAdministrator, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addContainerGap()))
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(layout.createSequentialGroup()
                    .addGap(0, 0, Short.MAX_VALUE)
                    .addComponent(pnlDeleteAdministrator, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGap(0, 0, Short.MAX_VALUE)))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 300, Short.MAX_VALUE)
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(layout.createSequentialGroup()
                    .addGap(0, 0, Short.MAX_VALUE)
                    .addComponent(pnlAddAdministrator, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGap(0, 0, Short.MAX_VALUE)))
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(layout.createSequentialGroup()
                    .addContainerGap()
                    .addComponent(pnlEditAdministrator, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addContainerGap()))
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(layout.createSequentialGroup()
                    .addGap(0, 0, Short.MAX_VALUE)
                    .addComponent(pnlDeleteAdministrator, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGap(0, 0, Short.MAX_VALUE)))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    /**
    * Disposes of this JDAministrator dialog and returns the user to the JFHome frame
    * @param evt 
    */
    private void btnCancelDeleteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCancelDeleteActionPerformed
        this.dispose();
    }//GEN-LAST:event_btnCancelDeleteActionPerformed

    /**
     * Finds staff object with specified ID and deletes it from the list
     * @param evt 
     */
    private void btnDeleteAdministratorActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnDeleteAdministratorActionPerformed
        for (Staff staff : UniSystems.getInstance().getStaffList()){
            if ((staff.getiD().equals(iD))){
                UniSystems.getInstance().deleteStaff(staff);
            }
        }
        this.parent.updateAdministrators(UniSystems.getInstance().getStaffList(), this.parent.getLstAdministrators());
        this.dispose();
    }//GEN-LAST:event_btnDeleteAdministratorActionPerformed

    /**
     * Calls the validateInputs method then creates a new administrator with the
     * field details and adds it to the list of staff then disposes of the JDialog
     * @param evt 
     */
    private void btnAddAdministratorActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAddAdministratorActionPerformed
        try {
            validateInputs(this.pnlAddAdministrator);
            Administrator newStaff;
            Integer iD = UniSystems.getInstance().getStaffList().size() + 1;
            String name = txtAddName.getText();
            String address = txtAddAddress.getText();
            VehicleAccessGroup vehicleAccessGroup = (VehicleAccessGroup) this.model.getSelectedItem();
            String password = txtAddPassword.getText();

            newStaff = new Administrator(iD, name, address, vehicleAccessGroup, password);
            this.parent.addAdministrator(newStaff);

            this.dispose();
        } catch (Exception ex){
            JOptionPane.showMessageDialog(this, ex.getMessage(), "Input error", JOptionPane.ERROR_MESSAGE);
        }
    }//GEN-LAST:event_btnAddAdministratorActionPerformed

    /**
    * Disposes of this JDAministrator dialog and returns the user to the JFHome frame
    * @param evt 
    */
    private void btnCancelAddActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCancelAddActionPerformed
        this.dispose();
    }//GEN-LAST:event_btnCancelAddActionPerformed

    /**
     * calls the validatesInputs methods then finds the staff member in the staff member list with the ID on the page checks if it's an
     * Administrator and changes it's properties. The breaks out of the loop. It then updates the list on the main panel and disposes of the JDialog
     * If there is an error in the fields you will get an error message from the validation method or the catch.
     * @param evt 
     */
    private void btnSaveEditActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSaveEditActionPerformed
        try {
            validateInputs(this.pnlEditAdministrator);
            for (Staff staff : UniSystems.getInstance().getStaffList()) {
                if (staff.getiD().equals(iD) && staff instanceof Administrator){
                    staff.setName(txtEditName.getText());
                    staff.setAddress(txtEditAddress.getText());
                    staff.setVehicleAccessGroup((VehicleAccessGroup) this.model.getSelectedItem());
                    ((Administrator) staff).setPassword(txtEditPassword.getText());
                    break;
                }
            }
            this.parent.updateAdministrators(UniSystems.getInstance().getStaffList(), this.parent.getLstAdministrators());
            this.dispose();
        } catch (Exception ex){
            JOptionPane.showMessageDialog(this, ex.getMessage(), "Input error", JOptionPane.ERROR_MESSAGE);
        }
    }//GEN-LAST:event_btnSaveEditActionPerformed

    /**
    * Disposes of this JDAministrator dialog and returns the user to the JFHome frame
    * @param evt 
    */
    private void btnCancelEditActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCancelEditActionPerformed
        this.dispose();
    }//GEN-LAST:event_btnCancelEditActionPerformed

    /**
     * Populates the fields on the edit administrator panel
     * @param staff 
     */
    public void showAdministrator(Staff staff){
        iD = staff.getiD();
        txtEditName.setText(staff.getName());
        txtEditAddress.setText(staff.getAddress());
        cmbEditVehicleAccessGroup.setSelectedItem(staff.getVehicleAccessGroup());
        if (staff instanceof Administrator){
            txtEditPassword.setText(((Administrator) staff).getPassword());
        }
    }
    
    /**
     * populates the fields on the delete administrator panel
     * @param staff 
     */
    public void showDeleteAdministrator(Staff staff){
        iD = staff.getiD();
        lblName.setText(staff.getName());
        lblAddress.setText(staff.getAddress());
        lblVehicleAccessGroup.setText(staff.getVehicleAccessGroup().toString());
        if (staff instanceof Administrator){
            lblPassword.setText(((Administrator) staff).getPassword());
        }
    }
    
    /**
     * Checks which panel we're building the array on the creates as array of components from inputs on the form then returns the array
     * @param panel
     * @return The array of components
     */
    public Component[] getInputFields(JPanel panel) {
        if (panel == pnlAddAdministrator){
            Component[] inputFields = {this.txtAddName, this.txtAddAddress, this.txtAddPassword};
            return inputFields;
        } else if (panel == pnlEditAdministrator){
            Component[] inputFields = {this.txtEditName, this.txtEditAddress, this.txtEditPassword};
            return inputFields;
        }
        return null;
    }
    
    /**
     * Assesses fields input by the user against pre-specified criteria such as fields being required and
     * format requirements
     * @param panel The panel that the user is currently on
     * @throws Exception exception based on input errors created by the user
     */
    public void validateInputs(JPanel panel) throws Exception {
        //validate code
        Boolean error = false;
        String errorMessage = "";
        Component[] inputFields = getInputFields(panel);
                
        String pattern = "^(?=.*[a-z])(?=.*[A-Z])(?=.*[0-9])(?=.*[!@#\\$%\\^&\\*])(?=.{8,})";

        Pattern regex = Pattern.compile(pattern);
        Matcher matches = regex.matcher(((javax.swing.JTextField)inputFields[2]).getText());
        
        if ("".equals(((javax.swing.JTextField)inputFields[0]).getText())){
            error = true;
            errorMessage = "No name entered.";
        } else if ("".equals(((javax.swing.JTextArea)inputFields[1]).getText())) {
            error = true;
            errorMessage = "No address entered.";
        } else if ("".equals(((javax.swing.JTextField)inputFields[2]).getText())){
            error = true;
            errorMessage = "No password entered.";
        } else if (!matches.find()){
            error = true;
            errorMessage = "Password must be at least 8 characters and contain 1 special character and 1 uppercase character.";
        }
        
        if (error) {
            throw new Exception(errorMessage);
        }
    }
    
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(JDAdministrator.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(JDAdministrator.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(JDAdministrator.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(JDAdministrator.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the dialog */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                JDAdministrator dialog = new JDAdministrator(new javax.swing.JFrame(), true);
                dialog.addWindowListener(new java.awt.event.WindowAdapter() {
                    @Override
                    public void windowClosing(java.awt.event.WindowEvent e) {
                        System.exit(0);
                    }
                });
                dialog.setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnAddAdministrator;
    private javax.swing.JButton btnCancelAdd;
    private javax.swing.JButton btnCancelDelete;
    private javax.swing.JButton btnCancelEdit;
    private javax.swing.JButton btnDeleteAdministrator;
    private javax.swing.JButton btnSaveEdit;
    private javax.swing.JComboBox cmbAddVehicleAccessGroup;
    private javax.swing.JComboBox cmbEditVehicleAccessGroup;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel22;
    private javax.swing.JLabel jLabel23;
    private javax.swing.JLabel jLabel24;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JLabel lblAddress;
    private javax.swing.JLabel lblName;
    private javax.swing.JLabel lblPassword;
    private javax.swing.JLabel lblVehicleAccessGroup;
    private javax.swing.JPanel pnlAddAdministrator;
    private javax.swing.JPanel pnlDeleteAdministrator;
    private javax.swing.JPanel pnlEditAdministrator;
    private javax.swing.JTextArea txtAddAddress;
    private javax.swing.JTextField txtAddName;
    private javax.swing.JTextField txtAddPassword;
    private javax.swing.JTextArea txtEditAddress;
    private javax.swing.JTextField txtEditName;
    private javax.swing.JTextField txtEditPassword;
    // End of variables declaration//GEN-END:variables
}
