/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package unisystems.gui;



import java.awt.BorderLayout;
import java.awt.Component;
import java.time.Instant;
import java.time.LocalDate;
import java.time.ZoneId;
import java.time.temporal.ChronoUnit;
import java.util.Date;
import javax.swing.DefaultComboBoxModel;
import javax.swing.JOptionPane;
import javax.swing.JPanel;
import unisystems.Car;
import unisystems.LongTermCar;
import unisystems.Service;
import unisystems.ShortTermCar;
import unisystems.TypeOfVehicle;
import unisystems.UniSystems;


/**
 *
 * @author Joseph Kellaway, Alex Murphy and Zakaria Robinson
 */
public class JDCar extends javax.swing.JDialog {

    private JFHome parent;
    private DefaultComboBoxModel<TypeOfVehicle> model =
            new DefaultComboBoxModel<>(TypeOfVehicle.values());
    private String registration;
    
    /**
     * Creates new form AddCars
     */
    public JDCar(java.awt.Frame parent, boolean modal) {
        super(parent, modal);
        initComponents();
    }
    
    /**
     * @param parent. This is the parent frame JFHome
     */
    public void setParent(JFHome parent) {
        this.parent = parent;
    }

    /**
     * @param panel. A string that determines which panel to add
     * Case statement that determines which panel to display
     */
    public void setPanel(String panel){
        switch (panel){
            case "add":
                changePanel(this.pnlAddCar);
                this.lblServiceDue.setText(LocalDate.now().plusYears(1).toString());
                break;
            case "edit":
                changePanel(this.pnlEditCar);
                break;
            case "delete":
                changePanel(this.pnlDeleteCar);
        }
    }
    
    /**
     * @param panel The panel to be displayed
     * Removes panels then displays the new panel
     */
    private void changePanel(JPanel panel) {
        getContentPane().removeAll();
        getContentPane().add(panel, BorderLayout.CENTER);
        getContentPane().doLayout();
        update(getGraphics());
    }
    
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        btngrpAddCarRentalLength = new javax.swing.ButtonGroup();
        btngrpEditCarRentalLength = new javax.swing.ButtonGroup();
        pnlDeleteCar = new javax.swing.JPanel();
        jLabel15 = new javax.swing.JLabel();
        lblDServiceDue = new javax.swing.JLabel();
        lblRegistration = new javax.swing.JLabel();
        lblMileage = new javax.swing.JLabel();
        lblMake = new javax.swing.JLabel();
        lblTypeOfVehicle = new javax.swing.JLabel();
        lblModel = new javax.swing.JLabel();
        btnDeleteCar = new javax.swing.JButton();
        jLabel22 = new javax.swing.JLabel();
        jLabel23 = new javax.swing.JLabel();
        jLabel24 = new javax.swing.JLabel();
        jLabel25 = new javax.swing.JLabel();
        jLabel26 = new javax.swing.JLabel();
        jLabel27 = new javax.swing.JLabel();
        btnCancelDelete = new javax.swing.JButton();
        jLabel28 = new javax.swing.JLabel();
        lblRentalLength = new javax.swing.JLabel();
        pnlAddCar = new javax.swing.JPanel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        txtAddMake = new javax.swing.JTextField();
        txtAddRegistration = new javax.swing.JTextField();
        btnAddCar = new javax.swing.JButton();
        txtAddModel = new javax.swing.JTextField();
        btnCancelAdd = new javax.swing.JButton();
        txtAddMileage = new javax.swing.JTextField();
        lblTitle = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        cmbAddTypeOfVehicle = new javax.swing.JComboBox();
        rdbAddShortTerm = new javax.swing.JRadioButton();
        rdbAddLongTerm = new javax.swing.JRadioButton();
        lblServiceDue = new javax.swing.JLabel();
        pnlEditCar = new javax.swing.JPanel();
        jLabel8 = new javax.swing.JLabel();
        btnSaveEdit = new javax.swing.JButton();
        jLabel9 = new javax.swing.JLabel();
        cmbEditTypeOfVehicle = new javax.swing.JComboBox();
        txtEditMake = new javax.swing.JTextField();
        dpEditServiceDue = new org.jdesktop.swingx.JXDatePicker();
        txtEditRegistration = new javax.swing.JTextField();
        rdbEditCarShortTerm = new javax.swing.JRadioButton();
        rdbEditCarLongTerm = new javax.swing.JRadioButton();
        txtEditModel = new javax.swing.JTextField();
        btnCancelEdit = new javax.swing.JButton();
        txtEditMileage = new javax.swing.JTextField();
        jLabel10 = new javax.swing.JLabel();
        jLabel11 = new javax.swing.JLabel();
        jLabel12 = new javax.swing.JLabel();
        jLabel13 = new javax.swing.JLabel();
        jLabel14 = new javax.swing.JLabel();
        btnAddService = new javax.swing.JButton();
        btnUpdateService = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);

        jLabel15.setText("DELETE CAR");

        lblDServiceDue.setText("lblDServiceDue");

        lblRegistration.setText("lblRegistration");

        lblMileage.setText("lblMileage");

        lblMake.setText("lblMake");

        lblTypeOfVehicle.setText("lblTypeOfVehicle");

        lblModel.setText("lblModel");

        btnDeleteCar.setText("Delete");
        btnDeleteCar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnDeleteCarActionPerformed(evt);
            }
        });

        jLabel22.setText("Registration");

        jLabel23.setText("Make");

        jLabel24.setText("Model");

        jLabel25.setText("Mileage");

        jLabel26.setText("Type Of Vehicle");

        jLabel27.setText("Next Service Due");

        btnCancelDelete.setText("Cancel");
        btnCancelDelete.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCancelDeleteActionPerformed(evt);
            }
        });

        jLabel28.setText("Rental Length");

        lblRentalLength.setText("lblRentalLength");

        javax.swing.GroupLayout pnlDeleteCarLayout = new javax.swing.GroupLayout(pnlDeleteCar);
        pnlDeleteCar.setLayout(pnlDeleteCarLayout);
        pnlDeleteCarLayout.setHorizontalGroup(
            pnlDeleteCarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlDeleteCarLayout.createSequentialGroup()
                .addGroup(pnlDeleteCarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(pnlDeleteCarLayout.createSequentialGroup()
                        .addComponent(jLabel15)
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addGroup(pnlDeleteCarLayout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(btnDeleteCar, javax.swing.GroupLayout.PREFERRED_SIZE, 125, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(btnCancelDelete, javax.swing.GroupLayout.PREFERRED_SIZE, 125, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap())
            .addGroup(pnlDeleteCarLayout.createSequentialGroup()
                .addGap(26, 26, 26)
                .addGroup(pnlDeleteCarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel25)
                    .addComponent(jLabel24)
                    .addComponent(jLabel23)
                    .addGroup(pnlDeleteCarLayout.createSequentialGroup()
                        .addGroup(pnlDeleteCarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel26)
                            .addComponent(jLabel27)
                            .addComponent(jLabel22)
                            .addComponent(jLabel28))
                        .addGap(103, 103, 103)
                        .addGroup(pnlDeleteCarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(lblRentalLength)
                            .addComponent(lblMake)
                            .addComponent(lblRegistration)
                            .addComponent(lblModel)
                            .addComponent(lblMileage)
                            .addComponent(lblTypeOfVehicle)
                            .addComponent(lblDServiceDue))))
                .addContainerGap(139, Short.MAX_VALUE))
        );
        pnlDeleteCarLayout.setVerticalGroup(
            pnlDeleteCarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlDeleteCarLayout.createSequentialGroup()
                .addComponent(jLabel15)
                .addGap(36, 36, 36)
                .addGroup(pnlDeleteCarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblRegistration)
                    .addComponent(jLabel22))
                .addGap(18, 18, 18)
                .addGroup(pnlDeleteCarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblMake)
                    .addComponent(jLabel23))
                .addGap(18, 18, 18)
                .addGroup(pnlDeleteCarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblModel)
                    .addComponent(jLabel24))
                .addGap(16, 16, 16)
                .addGroup(pnlDeleteCarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblMileage)
                    .addComponent(jLabel25))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(pnlDeleteCarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblTypeOfVehicle)
                    .addComponent(jLabel26))
                .addGap(18, 18, 18)
                .addGroup(pnlDeleteCarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblDServiceDue)
                    .addComponent(jLabel27))
                .addGap(18, 18, 18)
                .addGroup(pnlDeleteCarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel28)
                    .addComponent(lblRentalLength))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 52, Short.MAX_VALUE)
                .addGroup(pnlDeleteCarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnDeleteCar, javax.swing.GroupLayout.PREFERRED_SIZE, 45, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnCancelDelete, javax.swing.GroupLayout.PREFERRED_SIZE, 45, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap())
        );

        jLabel4.setText("Mileage:");

        jLabel5.setText("Type Of Vehicle:");

        jLabel6.setText("Next Service Due:");

        btnAddCar.setText("Save");
        btnAddCar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAddCarActionPerformed(evt);
            }
        });

        btnCancelAdd.setText("Cancel");
        btnCancelAdd.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCancelAddActionPerformed(evt);
            }
        });

        lblTitle.setText("ADD CAR");

        jLabel2.setText("Registration:");

        jLabel1.setText("Make:");

        jLabel3.setText("Model:");

        cmbAddTypeOfVehicle.setModel(model);
        cmbAddTypeOfVehicle.setSelectedItem(model);

        btngrpAddCarRentalLength.add(rdbAddShortTerm);
        rdbAddShortTerm.setSelected(true);
        rdbAddShortTerm.setText("Short Term Car");

        btngrpAddCarRentalLength.add(rdbAddLongTerm);
        rdbAddLongTerm.setText("Long Term Car");

        lblServiceDue.setText("lblServiceDue");

        javax.swing.GroupLayout pnlAddCarLayout = new javax.swing.GroupLayout(pnlAddCar);
        pnlAddCar.setLayout(pnlAddCarLayout);
        pnlAddCarLayout.setHorizontalGroup(
            pnlAddCarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlAddCarLayout.createSequentialGroup()
                .addComponent(lblTitle)
                .addGap(0, 0, Short.MAX_VALUE))
            .addGroup(pnlAddCarLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(pnlAddCarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(pnlAddCarLayout.createSequentialGroup()
                        .addComponent(btnAddCar, javax.swing.GroupLayout.PREFERRED_SIZE, 125, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(btnCancelAdd, javax.swing.GroupLayout.PREFERRED_SIZE, 125, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, pnlAddCarLayout.createSequentialGroup()
                        .addGroup(pnlAddCarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addGroup(pnlAddCarLayout.createSequentialGroup()
                                .addGroup(pnlAddCarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel2)
                                    .addComponent(jLabel1))
                                .addGap(130, 130, 130)
                                .addGroup(pnlAddCarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(txtAddMake)
                                    .addComponent(txtAddRegistration)))
                            .addGroup(javax.swing.GroupLayout.Alignment.LEADING, pnlAddCarLayout.createSequentialGroup()
                                .addGroup(pnlAddCarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel3)
                                    .addComponent(jLabel4))
                                .addGap(152, 152, 152)
                                .addGroup(pnlAddCarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(txtAddMileage)
                                    .addComponent(txtAddModel)))
                            .addGroup(javax.swing.GroupLayout.Alignment.LEADING, pnlAddCarLayout.createSequentialGroup()
                                .addGroup(pnlAddCarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel5)
                                    .addComponent(jLabel6))
                                .addGap(105, 105, 105)
                                .addGroup(pnlAddCarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(cmbAddTypeOfVehicle, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(lblServiceDue, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))))
                        .addGap(38, 38, 38)))
                .addContainerGap())
            .addGroup(pnlAddCarLayout.createSequentialGroup()
                .addGap(58, 58, 58)
                .addComponent(rdbAddShortTerm)
                .addGap(68, 68, 68)
                .addComponent(rdbAddLongTerm)
                .addContainerGap(110, Short.MAX_VALUE))
        );
        pnlAddCarLayout.setVerticalGroup(
            pnlAddCarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, pnlAddCarLayout.createSequentialGroup()
                .addComponent(lblTitle)
                .addGap(9, 9, 9)
                .addGroup(pnlAddCarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(txtAddRegistration, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(pnlAddCarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(txtAddMake))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(pnlAddCarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel3, javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(txtAddModel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 34, Short.MAX_VALUE)
                .addGroup(pnlAddCarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel4)
                    .addComponent(txtAddMileage, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 25, Short.MAX_VALUE)
                .addGroup(pnlAddCarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel5)
                    .addComponent(cmbAddTypeOfVehicle, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(pnlAddCarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel6)
                    .addComponent(lblServiceDue))
                .addGap(29, 29, 29)
                .addGroup(pnlAddCarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(rdbAddShortTerm)
                    .addComponent(rdbAddLongTerm))
                .addGap(28, 28, 28)
                .addGroup(pnlAddCarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnAddCar, javax.swing.GroupLayout.PREFERRED_SIZE, 45, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnCancelAdd, javax.swing.GroupLayout.PREFERRED_SIZE, 45, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap())
        );

        jLabel8.setText("EDIT CAR");

        btnSaveEdit.setText("Save");
        btnSaveEdit.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSaveEditActionPerformed(evt);
            }
        });

        jLabel9.setText("Next Service Due");

        cmbEditTypeOfVehicle.setModel(model);
        cmbEditTypeOfVehicle.setSelectedItem(model);

        btngrpEditCarRentalLength.add(rdbEditCarShortTerm);
        rdbEditCarShortTerm.setText("Short Term Car");

        btngrpEditCarRentalLength.add(rdbEditCarLongTerm);
        rdbEditCarLongTerm.setText("Long Term Car");

        btnCancelEdit.setText("Cancel");
        btnCancelEdit.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCancelEditActionPerformed(evt);
            }
        });

        jLabel10.setText("Registration");

        jLabel11.setText("Mileage");

        jLabel12.setText("Make");

        jLabel13.setText("Type Of Vehicle");

        jLabel14.setText("Model");

        btnAddService.setText("Add Service");
        btnAddService.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAddServiceActionPerformed(evt);
            }
        });

        btnUpdateService.setText("Complete Service");
        btnUpdateService.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnUpdateServiceActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout pnlEditCarLayout = new javax.swing.GroupLayout(pnlEditCar);
        pnlEditCar.setLayout(pnlEditCarLayout);
        pnlEditCarLayout.setHorizontalGroup(
            pnlEditCarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlEditCarLayout.createSequentialGroup()
                .addComponent(jLabel8)
                .addGap(0, 0, Short.MAX_VALUE))
            .addGroup(pnlEditCarLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(btnSaveEdit, javax.swing.GroupLayout.PREFERRED_SIZE, 125, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(btnAddService, javax.swing.GroupLayout.PREFERRED_SIZE, 125, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 21, Short.MAX_VALUE)
                .addComponent(btnUpdateService, javax.swing.GroupLayout.PREFERRED_SIZE, 125, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(btnCancelEdit, javax.swing.GroupLayout.PREFERRED_SIZE, 125, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, pnlEditCarLayout.createSequentialGroup()
                .addGap(65, 65, 65)
                .addComponent(rdbEditCarShortTerm)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(rdbEditCarLongTerm)
                .addGap(83, 83, 83))
            .addGroup(pnlEditCarLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(pnlEditCarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel11)
                    .addComponent(jLabel13)
                    .addComponent(jLabel9))
                .addGap(105, 105, 105)
                .addGroup(pnlEditCarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(dpEditServiceDue, javax.swing.GroupLayout.PREFERRED_SIZE, 331, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(pnlEditCarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                        .addComponent(txtEditMileage)
                        .addComponent(cmbEditTypeOfVehicle, 0, 331, Short.MAX_VALUE)))
                .addContainerGap(48, Short.MAX_VALUE))
            .addGroup(pnlEditCarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(pnlEditCarLayout.createSequentialGroup()
                    .addContainerGap()
                    .addGroup(pnlEditCarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                        .addGroup(pnlEditCarLayout.createSequentialGroup()
                            .addGroup(pnlEditCarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addComponent(jLabel10)
                                .addComponent(jLabel12))
                            .addGap(130, 130, 130)
                            .addGroup(pnlEditCarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addComponent(txtEditMake)
                                .addComponent(txtEditRegistration)))
                        .addGroup(javax.swing.GroupLayout.Alignment.LEADING, pnlEditCarLayout.createSequentialGroup()
                            .addComponent(jLabel14)
                            .addGap(160, 160, 160)
                            .addComponent(txtEditModel)))
                    .addGap(48, 48, 48)))
        );
        pnlEditCarLayout.setVerticalGroup(
            pnlEditCarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlEditCarLayout.createSequentialGroup()
                .addComponent(jLabel8)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 134, Short.MAX_VALUE)
                .addGroup(pnlEditCarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtEditMileage, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel11))
                .addGap(24, 24, 24)
                .addGroup(pnlEditCarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel13)
                    .addComponent(cmbEditTypeOfVehicle, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(33, 33, 33)
                .addGroup(pnlEditCarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel9)
                    .addComponent(dpEditServiceDue, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(26, 26, 26)
                .addGroup(pnlEditCarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(rdbEditCarLongTerm)
                    .addComponent(rdbEditCarShortTerm))
                .addGap(25, 25, 25)
                .addGroup(pnlEditCarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnSaveEdit, javax.swing.GroupLayout.PREFERRED_SIZE, 45, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnCancelEdit, javax.swing.GroupLayout.PREFERRED_SIZE, 45, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnAddService, javax.swing.GroupLayout.PREFERRED_SIZE, 45, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnUpdateService, javax.swing.GroupLayout.PREFERRED_SIZE, 45, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap())
            .addGroup(pnlEditCarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(pnlEditCarLayout.createSequentialGroup()
                    .addGap(34, 34, 34)
                    .addGroup(pnlEditCarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(jLabel10)
                        .addComponent(txtEditRegistration, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                    .addGroup(pnlEditCarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(jLabel12)
                        .addComponent(txtEditMake))
                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                    .addGroup(pnlEditCarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addComponent(jLabel14, javax.swing.GroupLayout.Alignment.TRAILING)
                        .addComponent(txtEditModel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGap(134, 134, 134)))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 450, Short.MAX_VALUE)
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(layout.createSequentialGroup()
                    .addContainerGap()
                    .addComponent(pnlDeleteCar, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addContainerGap()))
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(layout.createSequentialGroup()
                    .addContainerGap()
                    .addComponent(pnlAddCar, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addContainerGap()))
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(layout.createSequentialGroup()
                    .addGap(0, 0, Short.MAX_VALUE)
                    .addComponent(pnlEditCar, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGap(0, 0, Short.MAX_VALUE)))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 377, Short.MAX_VALUE)
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(layout.createSequentialGroup()
                    .addContainerGap()
                    .addComponent(pnlDeleteCar, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addContainerGap()))
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(layout.createSequentialGroup()
                    .addContainerGap()
                    .addComponent(pnlAddCar, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addContainerGap()))
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(layout.createSequentialGroup()
                    .addGap(0, 0, Short.MAX_VALUE)
                    .addComponent(pnlEditCar, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGap(0, 0, Short.MAX_VALUE)))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    
    /**
     * Calls the validateInputs method then creates a new car with the
     * field details and adds it to the list of cars then disposes of the JDialog.
     * Picks which sub-class of car to create based on which radio button is selected.
     * @param evt 
     */
    private void btnAddCarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAddCarActionPerformed
        try {
            validateInputs(this.pnlAddCar);
            Car newCar;
            String registration = this.txtAddRegistration.getText();
            String make = this.txtAddMake.getText();
            String modl = this.txtAddModel.getText();
            Integer mileage = Integer.parseInt(this.txtAddMileage.getText());
            TypeOfVehicle typeOfVehicle = (TypeOfVehicle) this.model.getSelectedItem();
            LocalDate serviceDue = LocalDate.now().plusYears(1);

            if (this.rdbAddLongTerm.isSelected()){
                newCar = new LongTermCar(registration, make, modl, true, false, mileage, serviceDue, typeOfVehicle, false);
            }else{
                newCar = new ShortTermCar(registration, make, modl, true, false, mileage, serviceDue, typeOfVehicle, false);
            }
            this.parent.addCar(newCar);

            this.parent.updateCar(UniSystems.getInstance().getCarList(), this.parent.getLstCars());
            this.dispose();
        } catch (Exception ex){
            JOptionPane.showMessageDialog(this, ex.getMessage(), "Input error", JOptionPane.ERROR_MESSAGE);
        }
    }//GEN-LAST:event_btnAddCarActionPerformed

    /**
    * Disposes of this JDCar dialog and returns the user to the JFHome frame
    * @param evt 
    */
    private void btnCancelAddActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCancelAddActionPerformed
        this.dispose();
    }//GEN-LAST:event_btnCancelAddActionPerformed

    
    /**
     * Calls the validateInputs method then reassigns the selected car with 
     * field details entered by the user then disposes of the JDialog.
     * Finds the car based on the locally saved registration variable relating 
     * to the loaded car (this allows the user to edit the registration without issues).
     * It also deletes and recreates the car if the car is moved from one loan type to the other.
     * @param evt 
     */
    private void btnSaveEditActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSaveEditActionPerformed
        try {
            validateInputs(this.pnlEditCar);
            String reg = this.txtEditRegistration.getText();
            String make = this.txtEditMake.getText();
            String modl = this.txtEditModel.getText();
            Integer mileage = Integer.parseInt(this.txtEditMileage.getText());
            TypeOfVehicle typeOfVehicle = (TypeOfVehicle) this.model.getSelectedItem();
            Date pickedDate = this.dpEditServiceDue.getDate();
            LocalDate serviceDue = pickedDate.toInstant().atZone(ZoneId.systemDefault()).toLocalDate();

            for (Car car : UniSystems.getInstance().getCarList()){
                if (car.getRegistration().equals(this.registration)){
                    Car oldCar = new ShortTermCar();
                    if (car instanceof LongTermCar) {
                        oldCar = new LongTermCar(car.getRegistration(), car.getMake(), car.getModel(), true, false, car.getMileage(), car.getServiceDue(), car.getTypeOfVehicle(), false);
                    } else if (car instanceof ShortTermCar) {
                        oldCar = new ShortTermCar(car.getRegistration(), car.getMake(), car.getModel(), true, false, car.getMileage(), car.getServiceDue(), car.getTypeOfVehicle(), false);
                    }
                    
                    if (car instanceof LongTermCar){
                        if (this.rdbEditCarShortTerm.isSelected()){
                            ShortTermCar newCar = new ShortTermCar(reg, make, modl, true, false, mileage, serviceDue, typeOfVehicle, false);
                            this.parent.editObject(oldCar, newCar);
                        } else {
                            LongTermCar newCar = new LongTermCar(reg, make, modl, true, false, mileage, serviceDue, typeOfVehicle, false);
                            this.parent.editObject(oldCar, newCar);
                        }
                    }else if (car instanceof ShortTermCar){
                        if (this.rdbEditCarLongTerm.isSelected()){
                            LongTermCar newCar = new LongTermCar(reg, make, modl, true, false, mileage, serviceDue, typeOfVehicle, false);
                            this.parent.editObject(oldCar, newCar);
                        } else {
                            ShortTermCar newCar = new ShortTermCar(reg, make, modl, true, false, mileage, serviceDue, typeOfVehicle, false);
                            this.parent.editObject(oldCar, newCar);
                        }
                    } else {
                        JOptionPane.showMessageDialog(null, "This is not a Short Term Car or a Long Term Car.");
                    }
                    break;
                }
            }
            this.parent.updateCar(UniSystems.getInstance().getCarList(), this.parent.getLstCars());
            this.dispose();
        } catch (Exception ex) {
            JOptionPane.showMessageDialog(this, ex.getMessage(), "Input error", JOptionPane.ERROR_MESSAGE);
        }
    }//GEN-LAST:event_btnSaveEditActionPerformed
    
    /**
    * Disposes of this JDCar dialog and returns the user to the JFHome frame
    * @param evt 
    */
    private void btnCancelEditActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCancelEditActionPerformed
        this.dispose();
    }//GEN-LAST:event_btnCancelEditActionPerformed

    /**
     * Deletes the selected car from the system. Sends the user back to the cars
     * panel on the JFHome frame.
     * @param evt 
     */
    private void btnDeleteCarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnDeleteCarActionPerformed
        for (Car car : UniSystems.getInstance().getCarList()){
             if (car.getRegistration().equals(this.lblRegistration.getText())){
                 this.parent.deleteObject(car);
             }
        }
        this.parent.updateCar(UniSystems.getInstance().getCarList(), this.parent.getLstCars());
        this.dispose();
    }//GEN-LAST:event_btnDeleteCarActionPerformed

    /**
    * Disposes of this JDCar dialog and returns the user to the JFHome frame
    * @param evt 
    */
    private void btnCancelDeleteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCancelDeleteActionPerformed
        this.dispose();
    }//GEN-LAST:event_btnCancelDeleteActionPerformed

    /**
     * Adds a service to the car currently being edited. Ensures that there is not
     * already an open service for the car. Before allowing the user to pick a service
     * date it offers to automatically set the service for today.
     * @param evt 
     */
    private void btnAddServiceActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAddServiceActionPerformed
        try {
            LocalDate date = LocalDate.now();
            for (Car car : UniSystems.getInstance().getCarList()){
                if (registration.equals(car.getRegistration())){
                    Boolean doDatesClash = false;
                    
                    for (Service service : car.getServiceHistory()) {
                        if (service.doDatesClash(date, date)) {
                            doDatesClash = true;
                            break;
                        }
                    }
                    
                    if (doDatesClash){
                        JOptionPane.showMessageDialog(this, "The vehicle is booked to be serviced.", "Dates clash", JOptionPane.ERROR_MESSAGE);
                    } else {
                        int messageDialog = JOptionPane.showConfirmDialog(this, "Send this car for service today?", "Book Service",JOptionPane.YES_NO_CANCEL_OPTION, JOptionPane.INFORMATION_MESSAGE);
                        if (messageDialog == JOptionPane.YES_OPTION) {
                            date = LocalDate.now();
                        } else if (messageDialog == JOptionPane.NO_OPTION) {
                            org.jdesktop.swingx.JXDatePicker datePicker = new org.jdesktop.swingx.JXDatePicker();
                            datePicker.setDate(Date.from(LocalDate.now().plus(1, ChronoUnit.DAYS).atStartOfDay(ZoneId.systemDefault()).toInstant()));
                            Object[] params = {"Select Date: ", datePicker};
                            int value = JOptionPane.showConfirmDialog(this, params, "Date", JOptionPane.OK_CANCEL_OPTION);
                            
                            if (value == JOptionPane.OK_OPTION) {
                                Date dateSelected = ((org.jdesktop.swingx.JXDatePicker)params[1]).getDate();
                                date = dateSelected.toInstant().atZone(ZoneId.systemDefault()).toLocalDate();
                            }    
                        }
                        car.addService(new Service(date));
                    }
                }
            }
        } catch (NullPointerException ex){
            JOptionPane.showMessageDialog(this, "A service date must be entered.", "Input error", JOptionPane.ERROR_MESSAGE);
        }
    }//GEN-LAST:event_btnAddServiceActionPerformed

    /**
     * Opens the JDService dialog to allow the user to complete the current service
     * @param evt 
     */
    private void btnUpdateServiceActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnUpdateServiceActionPerformed
        JDService objWindow = new JDService(null, true);
        objWindow.setParent(this);
        Service service = getService();
        if (service != null) {
            objWindow.showService(service, registration);
            objWindow.setVisible(true);
        } else {
            JOptionPane.showMessageDialog(this, "No incomplete services found.", "Service not found", JOptionPane.ERROR_MESSAGE);
        }
    }//GEN-LAST:event_btnUpdateServiceActionPerformed

    /**
     * Checks which panel we're building the array on the creates as array of components from inputs on the form then returns the array
     * @param panel
     * @return The array of components
     */
    public Component[] getInputFields(JPanel panel) {
        if (panel == pnlAddCar){
            Component[] inputFields = {this.txtAddRegistration, this.txtAddMake, this.txtAddModel, this.txtAddMileage};
            return inputFields;
        } else if (panel == pnlEditCar){
            Component[] inputFields = {this.txtEditRegistration, this.txtEditMake, this.txtEditModel, this.txtEditMileage, this.dpEditServiceDue};
            return inputFields;
        }
        return null;
    }
    
    /**
     * Assesses fields input by the user against pre-specified criteria such as fields being required and
     * format requirements
     * @param panel The panel that the user is currently on
     * @throws Exception exception based on input errors created by the user
     */
    public void validateInputs(JPanel panel) throws Exception {
        //validate code
        Boolean error = false;
        String errorMessage = "";
        
        Component[] inputFields = getInputFields(panel);
        
        for (Car car : UniSystems.getInstance().getCarList()) {
            if (!car.getRegistration().equals(this.registration)) {
                if (((javax.swing.JTextField)inputFields[0]).getText().equals(car.getRegistration())) {
                    error = true;
                    errorMessage = "Registration must be unique";
                }
            }
        }
        
        if ("".equals(((javax.swing.JTextField)inputFields[0]).getText())){
            error = true;
            errorMessage = "No registration entered.";
        } else if ("".equals(((javax.swing.JTextField)inputFields[1]).getText())) {
            error = true;
            errorMessage = "No make entered.";
        } else if ("".equals(((javax.swing.JTextField)inputFields[2]).getText())) {
            error = true;
            errorMessage = "No model entered.";
        } else if ("".equals(((javax.swing.JTextField)inputFields[3]).getText())) {
            error = true;
            errorMessage = "No mileage entered.";
        } else if (!"".equals(((javax.swing.JTextField)inputFields[3]).getText())){
            try {
                int a;
                a = Integer.parseInt(((javax.swing.JTextField)inputFields[3]).getText());              
            } catch (NumberFormatException ex){
                error = true;
                errorMessage = "Non-numeric characters entered into mileage field.";
            }
        }
        
        try {
            Instant today = LocalDate.now().plus(1, ChronoUnit.DAYS).atStartOfDay(ZoneId.systemDefault()).toInstant();
            if (((org.jdesktop.swingx.JXDatePicker)inputFields[4]).getDate() == null){
                error = true;
                errorMessage = "Date for next service must be entered.";
            } else if (((org.jdesktop.swingx.JXDatePicker)inputFields[4]).getDate().before(Date.from(today))) {
                error = true;
                errorMessage = "Date for next service must be after today's date.";
            }
        } catch (IndexOutOfBoundsException ex) {

        }
        if (error) {
            throw new Exception(errorMessage);
        }
    }
    
    /**
     * Finds any service relating to the car currently being edited
     * @return returns the open service
     */
    private Service getService(){
        Service foundService = null;
        for (Car car : UniSystems.getInstance().getCarList()){
            if (registration.equals(car.getRegistration())){
                if (car.getServiceHistory().getServiceHistory() != null) { //.getServiceHistory required twice due to itterator interface
                    for (Service service : car.getServiceHistory()){
                        if (service.getReturnDate() == null){
                            foundService = service;
                        }
                    } 
                }
            }
        }
        return foundService;
    }
    
    /**
     * Shows passed car on the edit car panel
     * @param car car to be edited
     */
    public void showCar(Car car) {
        LocalDate localDate = car.getServiceDue();
        Date serviceDue = Date.from(localDate.atStartOfDay(ZoneId.systemDefault()).toInstant());
        this.registration = car.getRegistration();
        this.txtEditRegistration.setText(this.registration);
        this.txtEditMake.setText(car.getMake());
        this.txtEditModel.setText(car.getModel());
        this.txtEditMileage.setText(car.getMileage().toString());
        this.cmbEditTypeOfVehicle.setSelectedItem(car.getTypeOfVehicle());
        this.dpEditServiceDue.setDate(serviceDue);
        
        if (car instanceof LongTermCar){
            this.rdbEditCarLongTerm.setSelected(true);
        } else if (car instanceof ShortTermCar) {
            this.rdbEditCarShortTerm.setSelected(true);
        } else {
            JOptionPane.showMessageDialog(null, "This is not a Short Term Car or a Long Term Car.");
        }
    }
    
    /**
     * Shows passed car on the delete car panel
     * @param car car to be deleted
     */
    public void showDeleteCar(Car car) {
        this.lblRegistration.setText(car.getRegistration());
        this.lblMake.setText(car.getMake());
        this.lblModel.setText(car.getModel());
        this.lblMileage.setText(car.getMileage().toString());
        this.lblTypeOfVehicle.setText(car.getTypeOfVehicle().toString());
        this.lblDServiceDue.setText(car.getServiceDue().toString());
        
        if (car instanceof ShortTermCar){
            this.lblRentalLength.setText("Short Term Car");
        }
        else if (car instanceof LongTermCar){
            this.lblRentalLength.setText("Long Term Car");
        }else{
            JOptionPane.showMessageDialog(null, "This is not a Short Term Car or a Long Term Car.");
        }
    }
    
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(JDCar.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(JDCar.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(JDCar.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(JDCar.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>

        /* Create and display the dialog */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                JDCar dialog = new JDCar(new javax.swing.JFrame(), true);
                dialog.addWindowListener(new java.awt.event.WindowAdapter() {
                    @Override
                    public void windowClosing(java.awt.event.WindowEvent e) {
                        System.exit(0);
                    }
                });
                dialog.setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnAddCar;
    private javax.swing.JButton btnAddService;
    private javax.swing.JButton btnCancelAdd;
    private javax.swing.JButton btnCancelDelete;
    private javax.swing.JButton btnCancelEdit;
    private javax.swing.JButton btnDeleteCar;
    private javax.swing.JButton btnSaveEdit;
    private javax.swing.JButton btnUpdateService;
    private javax.swing.ButtonGroup btngrpAddCarRentalLength;
    private javax.swing.ButtonGroup btngrpEditCarRentalLength;
    private javax.swing.JComboBox cmbAddTypeOfVehicle;
    private javax.swing.JComboBox cmbEditTypeOfVehicle;
    private org.jdesktop.swingx.JXDatePicker dpEditServiceDue;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel22;
    private javax.swing.JLabel jLabel23;
    private javax.swing.JLabel jLabel24;
    private javax.swing.JLabel jLabel25;
    private javax.swing.JLabel jLabel26;
    private javax.swing.JLabel jLabel27;
    private javax.swing.JLabel jLabel28;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JLabel lblDServiceDue;
    private javax.swing.JLabel lblMake;
    private javax.swing.JLabel lblMileage;
    private javax.swing.JLabel lblModel;
    private javax.swing.JLabel lblRegistration;
    private javax.swing.JLabel lblRentalLength;
    private javax.swing.JLabel lblServiceDue;
    private javax.swing.JLabel lblTitle;
    private javax.swing.JLabel lblTypeOfVehicle;
    private javax.swing.JPanel pnlAddCar;
    private javax.swing.JPanel pnlDeleteCar;
    private javax.swing.JPanel pnlEditCar;
    private javax.swing.JRadioButton rdbAddLongTerm;
    private javax.swing.JRadioButton rdbAddShortTerm;
    private javax.swing.JRadioButton rdbEditCarLongTerm;
    private javax.swing.JRadioButton rdbEditCarShortTerm;
    private javax.swing.JTextField txtAddMake;
    private javax.swing.JTextField txtAddMileage;
    private javax.swing.JTextField txtAddModel;
    private javax.swing.JTextField txtAddRegistration;
    private javax.swing.JTextField txtEditMake;
    private javax.swing.JTextField txtEditMileage;
    private javax.swing.JTextField txtEditModel;
    private javax.swing.JTextField txtEditRegistration;
    // End of variables declaration//GEN-END:variables
}