/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package unisystems.gui;

import command.Command;
import command.CommandTracker;
import command.CreateObjectCommand;
import command.DeleteObjectCommand;
import command.EditObjectCommand;
import command.interfaces.ICommand;
import command.interfaces.ICommandBehaviour;
import command.interfaces.ICommandTracker;
import java.awt.BorderLayout;
import java.io.BufferedOutputStream;
import java.io.File;
import java.io.FileOutputStream;
import java.io.IOException;
import java.io.ObjectOutputStream;
import java.util.ArrayList;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.DefaultListModel;
import javax.swing.JFileChooser;
import javax.swing.JList;
import javax.swing.JOptionPane;
import javax.swing.JPanel;
import unisystems.Administrator;
import unisystems.Car;
import unisystems.LongTermCar;
import unisystems.Rental;
import unisystems.Reservation;
import unisystems.ReservationState;
import unisystems.Staff;
import unisystems.StaffMember;
import unisystems.UniSystems;

/**
 *
 * @author Joseph Kellaway, Alex Murphy and Zakaria Robinson
 */
public class JFHome extends javax.swing.JFrame {

    private UniSystems uniSystem;
    public ICommandTracker objCmdTracker = new CommandTracker();
    private JPanel currentPanel = null;
    private ArrayList<Rental> currentRentalList = null;
    private ArrayList<Reservation> currentReservationList = null;
    private Integer login = -1;
    
    /**
     * Creates new form Home
     */
    public JFHome() {
        initComponents();
        uniSystem = UniSystems.getInstance();
        changePanel(pnlHome);
    }
    
    private void changePanel(JPanel panel) {
        getContentPane().removeAll();
        getContentPane().add(panel, BorderLayout.CENTER);
        getContentPane().doLayout();
        this.currentPanel = panel;
        update(getGraphics());
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        pnlHome = new javax.swing.JPanel();
        btnRentals = new javax.swing.JButton();
        btnStaff = new javax.swing.JButton();
        btnCars = new javax.swing.JButton();
        btnReservations = new javax.swing.JButton();
        btnAdministrator = new javax.swing.JButton();
        pnlRentals = new javax.swing.JPanel();
        jLabel3 = new javax.swing.JLabel();
        btnBack1 = new javax.swing.JButton();
        btnAddRental = new javax.swing.JButton();
        btnReturnRental = new javax.swing.JButton();
        btnReviewRental = new javax.swing.JButton();
        jScrollPane4 = new javax.swing.JScrollPane();
        lstRentals = new javax.swing.JList();
        pnlCars = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        btnBack = new javax.swing.JButton();
        btnAddCar = new javax.swing.JButton();
        btnEditCar = new javax.swing.JButton();
        btnDeleteCar = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        lstCars = new javax.swing.JList();
        pnlReservations = new javax.swing.JPanel();
        jLabel5 = new javax.swing.JLabel();
        btnBack3 = new javax.swing.JButton();
        btnNewReservation = new javax.swing.JButton();
        btnCancelReservation = new javax.swing.JButton();
        jScrollPane5 = new javax.swing.JScrollPane();
        lstReservations = new javax.swing.JList();
        pnlAdministrator = new javax.swing.JPanel();
        jScrollPane3 = new javax.swing.JScrollPane();
        lstAdministrator = new javax.swing.JList();
        btnEditAdmin = new javax.swing.JButton();
        btnDeleteAdmin = new javax.swing.JButton();
        btnBack5 = new javax.swing.JButton();
        btnAddAdmin = new javax.swing.JButton();
        jLabel7 = new javax.swing.JLabel();
        pnlStaff = new javax.swing.JPanel();
        jScrollPane2 = new javax.swing.JScrollPane();
        lstStaff = new javax.swing.JList();
        btnEditStaff = new javax.swing.JButton();
        btnDeleteStaff = new javax.swing.JButton();
        btnBack4 = new javax.swing.JButton();
        btnAddStaff = new javax.swing.JButton();
        jLabel6 = new javax.swing.JLabel();
        jMenuBar1 = new javax.swing.JMenuBar();
        mnuFile = new javax.swing.JMenu();
        mnuSave = new javax.swing.JMenuItem();
        jSeparator1 = new javax.swing.JPopupMenu.Separator();
        mnuExit = new javax.swing.JMenuItem();
        mnuEdit = new javax.swing.JMenu();
        mnuUndo = new javax.swing.JMenuItem();
        mnuRedo = new javax.swing.JMenuItem();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setMaximumSize(new java.awt.Dimension(650, 450));
        setMinimumSize(new java.awt.Dimension(650, 450));
        setResizable(false);
        setSize(new java.awt.Dimension(650, 450));
        addWindowListener(new java.awt.event.WindowAdapter() {
            public void windowClosing(java.awt.event.WindowEvent evt) {
                saveOnExit(evt);
            }
        });

        pnlHome.setMaximumSize(new java.awt.Dimension(600, 300));
        pnlHome.setMinimumSize(new java.awt.Dimension(600, 300));
        pnlHome.setPreferredSize(new java.awt.Dimension(600, 300));

        btnRentals.setText("Rentals");
        btnRentals.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnRentalsActionPerformed(evt);
            }
        });

        btnStaff.setText("Staff");
        btnStaff.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnStaffActionPerformed(evt);
            }
        });

        btnCars.setText("Cars");
        btnCars.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCarsActionPerformed(evt);
            }
        });

        btnReservations.setText("Reservations");
        btnReservations.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnReservationsActionPerformed(evt);
            }
        });

        btnAdministrator.setText("Administrator");
        btnAdministrator.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAdministratorActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout pnlHomeLayout = new javax.swing.GroupLayout(pnlHome);
        pnlHome.setLayout(pnlHomeLayout);
        pnlHomeLayout.setHorizontalGroup(
            pnlHomeLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, pnlHomeLayout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addComponent(btnAdministrator))
            .addGroup(pnlHomeLayout.createSequentialGroup()
                .addGap(83, 83, 83)
                .addGroup(pnlHomeLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(btnStaff, javax.swing.GroupLayout.PREFERRED_SIZE, 429, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnReservations, javax.swing.GroupLayout.PREFERRED_SIZE, 429, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnRentals, javax.swing.GroupLayout.PREFERRED_SIZE, 429, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnCars, javax.swing.GroupLayout.PREFERRED_SIZE, 429, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(88, Short.MAX_VALUE))
        );
        pnlHomeLayout.setVerticalGroup(
            pnlHomeLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlHomeLayout.createSequentialGroup()
                .addGap(62, 62, 62)
                .addComponent(btnRentals, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(btnReservations, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(btnCars, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(btnStaff, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 48, Short.MAX_VALUE)
                .addComponent(btnAdministrator, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(12, 12, 12))
        );

        pnlRentals.setMaximumSize(new java.awt.Dimension(600, 300));
        pnlRentals.setMinimumSize(new java.awt.Dimension(600, 300));
        pnlRentals.setPreferredSize(new java.awt.Dimension(600, 300));

        jLabel3.setText("RENTALS");

        btnBack1.setText("Back");
        btnBack1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnBack1ActionPerformed(evt);
            }
        });

        btnAddRental.setText("New Rental");
        btnAddRental.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAddRentalActionPerformed(evt);
            }
        });

        btnReturnRental.setText("Return Rental");
        btnReturnRental.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnReturnRentalActionPerformed(evt);
            }
        });

        btnReviewRental.setText("Review Rentals");
        btnReviewRental.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnReviewRentalActionPerformed(evt);
            }
        });

        jScrollPane4.setViewportView(lstRentals);

        javax.swing.GroupLayout pnlRentalsLayout = new javax.swing.GroupLayout(pnlRentals);
        pnlRentals.setLayout(pnlRentalsLayout);
        pnlRentalsLayout.setHorizontalGroup(
            pnlRentalsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, pnlRentalsLayout.createSequentialGroup()
                .addGroup(pnlRentalsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, pnlRentalsLayout.createSequentialGroup()
                        .addComponent(jLabel3)
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addGroup(pnlRentalsLayout.createSequentialGroup()
                        .addContainerGap()
                        .addGroup(pnlRentalsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jScrollPane4)
                            .addGroup(pnlRentalsLayout.createSequentialGroup()
                                .addComponent(btnAddRental, javax.swing.GroupLayout.PREFERRED_SIZE, 125, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)
                                .addComponent(btnReturnRental, javax.swing.GroupLayout.PREFERRED_SIZE, 125, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 74, Short.MAX_VALUE)
                                .addComponent(btnReviewRental, javax.swing.GroupLayout.PREFERRED_SIZE, 125, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)
                                .addComponent(btnBack1, javax.swing.GroupLayout.PREFERRED_SIZE, 125, javax.swing.GroupLayout.PREFERRED_SIZE)))))
                .addContainerGap())
        );
        pnlRentalsLayout.setVerticalGroup(
            pnlRentalsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlRentalsLayout.createSequentialGroup()
                .addComponent(jLabel3)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane4, javax.swing.GroupLayout.PREFERRED_SIZE, 254, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 48, Short.MAX_VALUE)
                .addGroup(pnlRentalsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnBack1, javax.swing.GroupLayout.PREFERRED_SIZE, 45, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnAddRental, javax.swing.GroupLayout.PREFERRED_SIZE, 45, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnReviewRental, javax.swing.GroupLayout.PREFERRED_SIZE, 45, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnReturnRental, javax.swing.GroupLayout.PREFERRED_SIZE, 45, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(40, 40, 40))
        );

        pnlCars.setMaximumSize(new java.awt.Dimension(600, 300));
        pnlCars.setMinimumSize(new java.awt.Dimension(600, 300));
        pnlCars.setPreferredSize(new java.awt.Dimension(600, 300));

        jLabel2.setText("CARS");

        btnBack.setText("Back");
        btnBack.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnBackActionPerformed(evt);
            }
        });

        btnAddCar.setText("Add Car");
        btnAddCar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAddCarActionPerformed(evt);
            }
        });

        btnEditCar.setText("Edit Car");
        btnEditCar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnEditCarActionPerformed(evt);
            }
        });

        btnDeleteCar.setText("Delete Car");
        btnDeleteCar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnDeleteCarActionPerformed(evt);
            }
        });

        jScrollPane1.setViewportView(lstCars);

        javax.swing.GroupLayout pnlCarsLayout = new javax.swing.GroupLayout(pnlCars);
        pnlCars.setLayout(pnlCarsLayout);
        pnlCarsLayout.setHorizontalGroup(
            pnlCarsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlCarsLayout.createSequentialGroup()
                .addComponent(jLabel2)
                .addGap(0, 0, Short.MAX_VALUE))
            .addGroup(pnlCarsLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(pnlCarsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 580, Short.MAX_VALUE)
                    .addGroup(pnlCarsLayout.createSequentialGroup()
                        .addComponent(btnAddCar, javax.swing.GroupLayout.PREFERRED_SIZE, 125, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(btnEditCar, javax.swing.GroupLayout.PREFERRED_SIZE, 125, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(26, 26, 26)
                        .addComponent(btnDeleteCar, javax.swing.GroupLayout.PREFERRED_SIZE, 125, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(btnBack, javax.swing.GroupLayout.PREFERRED_SIZE, 125, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap())
        );
        pnlCarsLayout.setVerticalGroup(
            pnlCarsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlCarsLayout.createSequentialGroup()
                .addComponent(jLabel2)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 206, Short.MAX_VALUE)
                .addGap(18, 18, 18)
                .addGroup(pnlCarsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(btnEditCar, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 45, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnDeleteCar, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 45, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(pnlCarsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(btnBack, javax.swing.GroupLayout.PREFERRED_SIZE, 45, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(btnAddCar, javax.swing.GroupLayout.PREFERRED_SIZE, 45, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap())
        );

        pnlReservations.setMaximumSize(new java.awt.Dimension(600, 300));
        pnlReservations.setMinimumSize(new java.awt.Dimension(600, 300));
        pnlReservations.setPreferredSize(new java.awt.Dimension(600, 300));

        jLabel5.setText("RESERVATIONS");

        btnBack3.setText("Back");
        btnBack3.setMaximumSize(new java.awt.Dimension(150, 23));
        btnBack3.setMinimumSize(new java.awt.Dimension(150, 23));
        btnBack3.setPreferredSize(new java.awt.Dimension(150, 23));
        btnBack3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnBack3ActionPerformed(evt);
            }
        });

        btnNewReservation.setText("New Reservation");
        btnNewReservation.setMaximumSize(new java.awt.Dimension(150, 23));
        btnNewReservation.setMinimumSize(new java.awt.Dimension(150, 23));
        btnNewReservation.setPreferredSize(new java.awt.Dimension(150, 23));
        btnNewReservation.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnNewReservationActionPerformed(evt);
            }
        });

        btnCancelReservation.setText("Cancel Reservation");
        btnCancelReservation.setMaximumSize(new java.awt.Dimension(150, 23));
        btnCancelReservation.setMinimumSize(new java.awt.Dimension(150, 23));
        btnCancelReservation.setPreferredSize(new java.awt.Dimension(150, 23));
        btnCancelReservation.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCancelReservationActionPerformed(evt);
            }
        });

        jScrollPane5.setViewportView(lstReservations);

        javax.swing.GroupLayout pnlReservationsLayout = new javax.swing.GroupLayout(pnlReservations);
        pnlReservations.setLayout(pnlReservationsLayout);
        pnlReservationsLayout.setHorizontalGroup(
            pnlReservationsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlReservationsLayout.createSequentialGroup()
                .addComponent(jLabel5)
                .addGap(0, 0, Short.MAX_VALUE))
            .addGroup(pnlReservationsLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(pnlReservationsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane5, javax.swing.GroupLayout.DEFAULT_SIZE, 610, Short.MAX_VALUE)
                    .addGroup(pnlReservationsLayout.createSequentialGroup()
                        .addComponent(btnNewReservation, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(btnCancelReservation, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(79, 79, 79)
                        .addComponent(btnBack3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap())
        );
        pnlReservationsLayout.setVerticalGroup(
            pnlReservationsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlReservationsLayout.createSequentialGroup()
                .addComponent(jLabel5)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane5, javax.swing.GroupLayout.DEFAULT_SIZE, 294, Short.MAX_VALUE)
                .addGap(18, 18, 18)
                .addGroup(pnlReservationsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(pnlReservationsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(btnBack3, javax.swing.GroupLayout.PREFERRED_SIZE, 45, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(btnCancelReservation, javax.swing.GroupLayout.PREFERRED_SIZE, 45, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(btnNewReservation, javax.swing.GroupLayout.PREFERRED_SIZE, 45, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(30, 30, 30))
        );

        pnlAdministrator.setMaximumSize(new java.awt.Dimension(600, 300));
        pnlAdministrator.setMinimumSize(new java.awt.Dimension(600, 300));
        pnlAdministrator.setPreferredSize(new java.awt.Dimension(600, 300));

        jScrollPane3.setViewportView(lstAdministrator);

        btnEditAdmin.setText("Edit Admin");
        btnEditAdmin.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnEditAdminActionPerformed(evt);
            }
        });

        btnDeleteAdmin.setText("Delete Admin");
        btnDeleteAdmin.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnDeleteAdminActionPerformed(evt);
            }
        });

        btnBack5.setText("Back");
        btnBack5.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnBack5ActionPerformed(evt);
            }
        });

        btnAddAdmin.setText("Add Admin");
        btnAddAdmin.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAddAdminActionPerformed(evt);
            }
        });

        jLabel7.setText("ADMINISTRATOR");

        javax.swing.GroupLayout pnlAdministratorLayout = new javax.swing.GroupLayout(pnlAdministrator);
        pnlAdministrator.setLayout(pnlAdministratorLayout);
        pnlAdministratorLayout.setHorizontalGroup(
            pnlAdministratorLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlAdministratorLayout.createSequentialGroup()
                .addComponent(jLabel7)
                .addGap(0, 0, Short.MAX_VALUE))
            .addGroup(pnlAdministratorLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(pnlAdministratorLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane3)
                    .addGroup(pnlAdministratorLayout.createSequentialGroup()
                        .addComponent(btnAddAdmin, javax.swing.GroupLayout.PREFERRED_SIZE, 125, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 33, Short.MAX_VALUE)
                        .addComponent(btnEditAdmin, javax.swing.GroupLayout.PREFERRED_SIZE, 125, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(btnDeleteAdmin, javax.swing.GroupLayout.PREFERRED_SIZE, 125, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(29, 29, 29)
                        .addComponent(btnBack5, javax.swing.GroupLayout.PREFERRED_SIZE, 125, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap())
        );
        pnlAdministratorLayout.setVerticalGroup(
            pnlAdministratorLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlAdministratorLayout.createSequentialGroup()
                .addComponent(jLabel7)
                .addGap(13, 13, 13)
                .addComponent(jScrollPane3, javax.swing.GroupLayout.DEFAULT_SIZE, 206, Short.MAX_VALUE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(pnlAdministratorLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnBack5, javax.swing.GroupLayout.PREFERRED_SIZE, 45, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnEditAdmin, javax.swing.GroupLayout.PREFERRED_SIZE, 45, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnDeleteAdmin, javax.swing.GroupLayout.PREFERRED_SIZE, 45, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnAddAdmin, javax.swing.GroupLayout.PREFERRED_SIZE, 45, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap())
        );

        pnlStaff.setMaximumSize(new java.awt.Dimension(600, 300));
        pnlStaff.setMinimumSize(new java.awt.Dimension(600, 300));
        pnlStaff.setPreferredSize(new java.awt.Dimension(600, 300));

        jScrollPane2.setViewportView(lstStaff);

        btnEditStaff.setText("Edit Staff");
        btnEditStaff.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnEditStaffActionPerformed(evt);
            }
        });

        btnDeleteStaff.setText("Delete Staff");
        btnDeleteStaff.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnDeleteStaffActionPerformed(evt);
            }
        });

        btnBack4.setText("Back");
        btnBack4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnBack4ActionPerformed(evt);
            }
        });

        btnAddStaff.setText("Add Staff");
        btnAddStaff.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAddStaffActionPerformed(evt);
            }
        });

        jLabel6.setText("STAFF");

        javax.swing.GroupLayout pnlStaffLayout = new javax.swing.GroupLayout(pnlStaff);
        pnlStaff.setLayout(pnlStaffLayout);
        pnlStaffLayout.setHorizontalGroup(
            pnlStaffLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlStaffLayout.createSequentialGroup()
                .addComponent(jLabel6)
                .addGap(0, 0, Short.MAX_VALUE))
            .addGroup(pnlStaffLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(pnlStaffLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane2)
                    .addGroup(pnlStaffLayout.createSequentialGroup()
                        .addComponent(btnAddStaff, javax.swing.GroupLayout.PREFERRED_SIZE, 125, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(31, 31, 31)
                        .addComponent(btnEditStaff, javax.swing.GroupLayout.PREFERRED_SIZE, 125, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(btnDeleteStaff, javax.swing.GroupLayout.PREFERRED_SIZE, 125, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 61, Short.MAX_VALUE)
                        .addComponent(btnBack4, javax.swing.GroupLayout.PREFERRED_SIZE, 125, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap())
        );
        pnlStaffLayout.setVerticalGroup(
            pnlStaffLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlStaffLayout.createSequentialGroup()
                .addComponent(jLabel6)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane2, javax.swing.GroupLayout.DEFAULT_SIZE, 313, Short.MAX_VALUE)
                .addGap(18, 18, 18)
                .addGroup(pnlStaffLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnBack4, javax.swing.GroupLayout.PREFERRED_SIZE, 45, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnEditStaff, javax.swing.GroupLayout.PREFERRED_SIZE, 45, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnDeleteStaff, javax.swing.GroupLayout.PREFERRED_SIZE, 45, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnAddStaff, javax.swing.GroupLayout.PREFERRED_SIZE, 45, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap())
        );

        mnuFile.setText("File");

        mnuSave.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_S, java.awt.event.InputEvent.CTRL_MASK));
        mnuSave.setText("Save UniSystems");
        mnuSave.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mnuSaveActionPerformed(evt);
            }
        });
        mnuFile.add(mnuSave);
        mnuFile.add(jSeparator1);

        mnuExit.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_X, java.awt.event.InputEvent.CTRL_MASK));
        mnuExit.setText("Exit");
        mnuExit.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mnuExitActionPerformed(evt);
            }
        });
        mnuFile.add(mnuExit);

        jMenuBar1.add(mnuFile);

        mnuEdit.setText("Edit");

        mnuUndo.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_Z, java.awt.event.InputEvent.CTRL_MASK));
        mnuUndo.setText("Undo");
        mnuUndo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mnuUndoActionPerformed(evt);
            }
        });
        mnuEdit.add(mnuUndo);

        mnuRedo.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_Y, java.awt.event.InputEvent.CTRL_MASK));
        mnuRedo.setText("Redo");
        mnuRedo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mnuRedoActionPerformed(evt);
            }
        });
        mnuEdit.add(mnuRedo);

        jMenuBar1.add(mnuEdit);

        setJMenuBar(jMenuBar1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 650, Short.MAX_VALUE)
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(layout.createSequentialGroup()
                    .addContainerGap()
                    .addComponent(pnlHome, javax.swing.GroupLayout.DEFAULT_SIZE, 630, Short.MAX_VALUE)
                    .addContainerGap()))
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(layout.createSequentialGroup()
                    .addContainerGap()
                    .addComponent(pnlRentals, javax.swing.GroupLayout.DEFAULT_SIZE, 630, Short.MAX_VALUE)
                    .addContainerGap()))
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(layout.createSequentialGroup()
                    .addGap(0, 0, Short.MAX_VALUE)
                    .addComponent(pnlCars, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGap(0, 0, Short.MAX_VALUE)))
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(layout.createSequentialGroup()
                    .addContainerGap()
                    .addComponent(pnlReservations, javax.swing.GroupLayout.DEFAULT_SIZE, 630, Short.MAX_VALUE)
                    .addContainerGap()))
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(layout.createSequentialGroup()
                    .addGap(0, 0, Short.MAX_VALUE)
                    .addComponent(pnlAdministrator, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGap(0, 0, Short.MAX_VALUE)))
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(layout.createSequentialGroup()
                    .addContainerGap()
                    .addComponent(pnlStaff, javax.swing.GroupLayout.DEFAULT_SIZE, 630, Short.MAX_VALUE)
                    .addContainerGap()))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 429, Short.MAX_VALUE)
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(layout.createSequentialGroup()
                    .addContainerGap()
                    .addComponent(pnlHome, javax.swing.GroupLayout.DEFAULT_SIZE, 407, Short.MAX_VALUE)
                    .addContainerGap()))
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(layout.createSequentialGroup()
                    .addContainerGap()
                    .addComponent(pnlRentals, javax.swing.GroupLayout.DEFAULT_SIZE, 407, Short.MAX_VALUE)
                    .addContainerGap()))
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(layout.createSequentialGroup()
                    .addGap(0, 0, Short.MAX_VALUE)
                    .addComponent(pnlCars, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGap(0, 0, Short.MAX_VALUE)))
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(layout.createSequentialGroup()
                    .addContainerGap()
                    .addComponent(pnlReservations, javax.swing.GroupLayout.DEFAULT_SIZE, 407, Short.MAX_VALUE)
                    .addContainerGap()))
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(layout.createSequentialGroup()
                    .addGap(0, 0, Short.MAX_VALUE)
                    .addComponent(pnlAdministrator, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGap(0, 0, Short.MAX_VALUE)))
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(layout.createSequentialGroup()
                    .addContainerGap()
                    .addComponent(pnlStaff, javax.swing.GroupLayout.DEFAULT_SIZE, 407, Short.MAX_VALUE)
                    .addContainerGap()))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnRentalsActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnRentalsActionPerformed
        changePanel(pnlRentals);
        updateRentals();
    }//GEN-LAST:event_btnRentalsActionPerformed

    private void btnStaffActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnStaffActionPerformed
        changePanel(pnlStaff);
        updateStaffMember(uniSystem.getStaffList(), lstStaff);
    }//GEN-LAST:event_btnStaffActionPerformed

    private void btnCarsActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCarsActionPerformed
        changePanel(pnlCars);
        updateCar(uniSystem.getCarList(), lstCars);
    }//GEN-LAST:event_btnCarsActionPerformed

    private void btnReservationsActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnReservationsActionPerformed
        changePanel(pnlReservations);
    }//GEN-LAST:event_btnReservationsActionPerformed

    private void btnBack1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnBack1ActionPerformed
        changePanel(pnlHome);
    }//GEN-LAST:event_btnBack1ActionPerformed

    private void btnBack3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnBack3ActionPerformed
        changePanel(pnlHome);
    }//GEN-LAST:event_btnBack3ActionPerformed

    private void btnBack4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnBack4ActionPerformed
        changePanel(pnlHome);
    }//GEN-LAST:event_btnBack4ActionPerformed

    private void btnAddStaffActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAddStaffActionPerformed
        JDStaff objWindow = new JDStaff(null, true);
        objWindow.setParent(this);
        objWindow.setPanel("add");
        objWindow.setVisible(true);
    }//GEN-LAST:event_btnAddStaffActionPerformed

    private void btnEditStaffActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnEditStaffActionPerformed
        try {
            validateInputs(pnlStaff);
            JDStaff objWindow = new JDStaff(null, true);
            objWindow.setParent(this);
            objWindow.setPanel("edit");
            objWindow.showStaff((Staff)this.lstStaff.getSelectedValue());
            objWindow.setVisible(true);
        } catch (Exception ex){
            JOptionPane.showMessageDialog(this, ex.getMessage(), "Input error", JOptionPane.ERROR_MESSAGE);
        }
    }//GEN-LAST:event_btnEditStaffActionPerformed

    private void btnDeleteStaffActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnDeleteStaffActionPerformed
        try {
            validateInputs(pnlStaff);
            JDStaff objWindow = new JDStaff(null, true);
            objWindow.setParent(this);
            objWindow.setPanel("delete");
            objWindow.showDeleteStaff((Staff)this.lstStaff.getSelectedValue());
            objWindow.setVisible(true);
        } catch (Exception ex){
            JOptionPane.showMessageDialog(this, ex.getMessage(), "Input error", JOptionPane.ERROR_MESSAGE);
        }
    }//GEN-LAST:event_btnDeleteStaffActionPerformed

    private void btnAddRentalActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAddRentalActionPerformed
        JDRental objWindow = new JDRental(null, true);
        objWindow.setParent(this);
        objWindow.setPanel("add");
        objWindow.setVisible(true);
    }//GEN-LAST:event_btnAddRentalActionPerformed

    private void btnReturnRentalActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnReturnRentalActionPerformed
        try {
            validateInputs(pnlRentals);
            JDRental objWindow = new JDRental(null, true);
            objWindow.setParent(this);
            objWindow.setRental(this.currentRentalList.get(lstRentals.getSelectedIndex()));
            objWindow.setPanel("return");
            objWindow.setVisible(true);
        } catch (Exception ex){
            JOptionPane.showMessageDialog(this, ex.getMessage(), "Input error", JOptionPane.ERROR_MESSAGE);
        }
    }//GEN-LAST:event_btnReturnRentalActionPerformed

    private void btnReviewRentalActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnReviewRentalActionPerformed
        JDRental objWindow = new JDRental(null, true);
        objWindow.setParent(this);
        objWindow.setPanel("review");
        objWindow.setVisible(true);
    }//GEN-LAST:event_btnReviewRentalActionPerformed

    private void btnAdministratorActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAdministratorActionPerformed
        changePanel(pnlAdministrator);
        updateAdministrators(uniSystem.getStaffList(), lstAdministrator);
    }//GEN-LAST:event_btnAdministratorActionPerformed

    private void btnEditAdminActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnEditAdminActionPerformed
        try {
            validateInputs(pnlAdministrator);
            JDAdministrator objWindow = new JDAdministrator(null, true);
            objWindow.setParent(this);
            objWindow.setPanel("edit");
            objWindow.showAdministrator((Staff)lstAdministrator.getSelectedValue());
            objWindow.setVisible(true);
        } catch (Exception ex){
            JOptionPane.showMessageDialog(this, ex.getMessage(), "Input error", JOptionPane.ERROR_MESSAGE);
        }
    }//GEN-LAST:event_btnEditAdminActionPerformed

    private void btnDeleteAdminActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnDeleteAdminActionPerformed
        try {
            validateInputs(pnlAdministrator);
            JDAdministrator objWindow = new JDAdministrator(null, true);
            objWindow.setParent(this);
            objWindow.setPanel("delete");
            objWindow.showDeleteAdministrator((Staff)lstAdministrator.getSelectedValue());
            objWindow.setVisible(true);
        } catch (Exception ex){
            JOptionPane.showMessageDialog(this, ex.getMessage(), "Input error", JOptionPane.ERROR_MESSAGE);
        }
    }//GEN-LAST:event_btnDeleteAdminActionPerformed

    private void btnBack5ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnBack5ActionPerformed
        changePanel(pnlHome);
    }//GEN-LAST:event_btnBack5ActionPerformed

    private void btnAddAdminActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAddAdminActionPerformed
        JDAdministrator objWindow = new JDAdministrator(null, true);
        objWindow.setParent(this);
        objWindow.setPanel("add");
        objWindow.setVisible(true);
    }//GEN-LAST:event_btnAddAdminActionPerformed

    private void mnuUndoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mnuUndoActionPerformed
        this.objCmdTracker.undoLastCommand();
        if (currentPanel == pnlAdministrator){
            this.updateAdministrators(UniSystems.getInstance().getStaffList(), this.getLstAdministrators());
        }else if (currentPanel == pnlCars){
            this.updateCar(UniSystems.getInstance().getCarList(), this.getLstCars());
        } else if (currentPanel == pnlStaff){
            this.updateStaffMember(UniSystems.getInstance().getStaffList(), this.getLstStaff());
        } else if (currentPanel == pnlRentals){
            updateRentals();
        }
        changePanel(this.currentPanel);
    }//GEN-LAST:event_mnuUndoActionPerformed

    private void mnuExitActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mnuExitActionPerformed
        this.dispose();
    }//GEN-LAST:event_mnuExitActionPerformed
    
    private void mnuSaveActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mnuSaveActionPerformed
        saveUniSystemsData();
    }//GEN-LAST:event_mnuSaveActionPerformed

    private void mnuRedoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mnuRedoActionPerformed
        this.objCmdTracker.redoLastCommand();
        if (currentPanel == pnlAdministrator){
            this.updateAdministrators(UniSystems.getInstance().getStaffList(), this.getLstAdministrators());
        }else if (currentPanel == pnlCars){
                this.updateCar(UniSystems.getInstance().getCarList(), this.getLstCars());
        } else if (currentPanel == pnlStaff){
                this.updateStaffMember(UniSystems.getInstance().getStaffList(), this.getLstStaff());
        } else if (currentPanel == pnlRentals){
                updateRentals();
            }
        changePanel(this.currentPanel);
    }//GEN-LAST:event_mnuRedoActionPerformed

    private void btnNewReservationActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnNewReservationActionPerformed
        JDReservation objWindow = new JDReservation(null, true);
        objWindow.setParent(this);
        objWindow.setPanel("add");
        objWindow.setVisible(true);
    }//GEN-LAST:event_btnNewReservationActionPerformed

    private void btnCancelReservationActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCancelReservationActionPerformed
        try {
            validateInputs(pnlReservations);
            JDReservation objWindow = new JDReservation(null, true);
            objWindow.setParent(this);
            objWindow.showReservation(this.currentReservationList.get(lstReservations.getSelectedIndex()));
            objWindow.setPanel("cancel");
            objWindow.setVisible(true);
        } catch (Exception ex){
            JOptionPane.showMessageDialog(this, ex.getMessage(), "Input error", JOptionPane.ERROR_MESSAGE);
        }
    }//GEN-LAST:event_btnCancelReservationActionPerformed

    private void btnDeleteCarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnDeleteCarActionPerformed
        try {
            validateInputs(pnlCars);
            JDCar objWindow = new JDCar(null, true);
            objWindow.setParent(this);
            objWindow.setPanel("delete");
            objWindow.showDeleteCar((Car)lstCars.getSelectedValue());
            objWindow.setVisible(true);
        } catch (Exception ex){
            JOptionPane.showMessageDialog(this, ex.getMessage(), "Input error", JOptionPane.ERROR_MESSAGE);
        }
    }//GEN-LAST:event_btnDeleteCarActionPerformed

    private void btnEditCarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnEditCarActionPerformed
        try {
            validateInputs(pnlCars);
            JDCar objWindow = new JDCar(null, true);
            objWindow.setParent(this);
            objWindow.setPanel("edit");
            objWindow.showCar((Car)lstCars.getSelectedValue());
            objWindow.setVisible(true);
        } catch (Exception ex){
            JOptionPane.showMessageDialog(this, ex.getMessage(), "Input error", JOptionPane.ERROR_MESSAGE);
        }
    }//GEN-LAST:event_btnEditCarActionPerformed

    private void btnAddCarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAddCarActionPerformed
        JDCar objWindow = new JDCar(null, true);
        objWindow.setParent(this);
        objWindow.setPanel("add");
        objWindow.setVisible(true);
    }//GEN-LAST:event_btnAddCarActionPerformed

    private void btnBackActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnBackActionPerformed
        changePanel(pnlHome);
    }//GEN-LAST:event_btnBackActionPerformed

    private void saveOnExit(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_saveOnExit
        if (UniSystems.getInstance().getLastCommand() != null) {
            int response;
            response = JOptionPane.showConfirmDialog(this, "Changed have been made, would you like to save?", "Save Changes", JOptionPane.OK_CANCEL_OPTION);
            if (response == JOptionPane.OK_OPTION) {
                this.saveUniSystemsData();
            }
        }
    }//GEN-LAST:event_saveOnExit

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(JFHome.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(JFHome.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(JFHome.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(JFHome.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new JFHome().setVisible(true);
            }
        });
    }

    public void setUniSystem(UniSystems uniSystem) {
        this.uniSystem = uniSystem;
    }

    public final void updateCar(ArrayList arlList, JList locList){
        DefaultListModel<Object> newModel = new DefaultListModel<>();
        for (Object currObject: arlList){
            newModel.addElement(currObject);
        }
        locList.setModel(newModel);
    }
    
    public void updateRentals(){
        this.currentRentalList = new ArrayList<>();
        DefaultListModel<Object> newModel = new DefaultListModel<>();
        ArrayList<Car> arlCarList = UniSystems.getInstance().getCarList();

        for (Car car : arlCarList){
            for (Rental rental : car.getRentalHistory()){
                if (rental.getDateReturned() == null)
                {
                    this.currentRentalList.add(rental);
                    newModel.addElement(car.getRegistration() + " rented by " + rental);
                }
            }
        }
        this.lstRentals.setModel(newModel);
    }
    
    public void updateReservations(){
        this.currentReservationList = new ArrayList<>();
        DefaultListModel<Object> newModel = new DefaultListModel<>();
        ArrayList<Car> arlCarList = UniSystems.getInstance().getCarList();
        
        for (Car car : arlCarList){
            if (car instanceof LongTermCar){
                for (Reservation reservation : ((LongTermCar) car).getArlReservationList()){
                    if (reservation.getState().equals(ReservationState.OPEN)){
                        this.currentReservationList.add(reservation);
                        newModel.addElement(car.getRegistration() + " reserved by " + reservation);
                    }
                }
            }
        }
        this.lstReservations.setModel(newModel);
    }
    
    public final void updateAdministrators(ArrayList arlList, JList locList){
        DefaultListModel<Object> newModel = new DefaultListModel<>();
        for (Object currObject: arlList){
            if (currObject instanceof Administrator){
                newModel.addElement(currObject);
            }
        }
        locList.setModel(newModel);
    }
    
    public final void updateStaffMember(ArrayList arlList, JList locList){
        DefaultListModel<Object> newModel = new DefaultListModel<>();
        for (Object currObject: arlList){
            if (currObject instanceof StaffMember){
                newModel.addElement(currObject);
            }
        }
        locList.setModel(newModel);
    }
    
    public void addStaffMember(Staff newStaff){
        createObject(newStaff);
        updateStaffMember(this.uniSystem.getStaffList(), lstStaff);
    }
    
    public void addAdministrator(Staff newStaff){
        createObject(newStaff);
        updateAdministrators(this.uniSystem.getStaffList(), lstAdministrator); 
    }
    
    public void addCar(Car newCar){
        createObject(newCar);
        updateCar(this.uniSystem.getCarList(), lstCars);
    }
    
    public JList getLstCars(){
        return lstCars;
    }
    
    public JList getLstStaff(){
        return lstStaff;
    }
    
    public JList getLstAdministrators(){
        return lstAdministrator;
    }
    
    public void buttonVisibility(Boolean visibility){
        btnAdministrator.setVisible(visibility);
    }

    private void saveUniSystemsData() {
        //Save dialogue
        JFileChooser objFileDialogue = new JFileChooser();
        int intDialogResult = JFileChooser.CANCEL_OPTION;
        intDialogResult = objFileDialogue.showSaveDialog(this);
        
        //Test correction option chosen and save accordingly
        if (intDialogResult == JFileChooser.APPROVE_OPTION){
            File objFile = objFileDialogue.getSelectedFile();
            
            try (ObjectOutputStream objOut = new ObjectOutputStream(
            new BufferedOutputStream(new FileOutputStream(objFile)))){
                
                objOut.writeObject(UniSystems.getInstance());
                JOptionPane.showMessageDialog(this, "UniSystem data saved.",
                        "Save completed.", JOptionPane.INFORMATION_MESSAGE);
            } catch (IOException ex){
                Logger.getLogger(JFHome.class.getName()).log(Level.SEVERE, null, ex);
                JOptionPane.showMessageDialog(this, "Error saving data model.",
                "File save error: " + ex.getMessage(), JOptionPane.ERROR_MESSAGE);
            }
        } else {
            JOptionPane.showMessageDialog(this,"Save operation cancelled.",
                    "Operation aborted.", JOptionPane.ERROR_MESSAGE);
        }
    }

    public Boolean createObject(Object objToCreate) {
        ICommandBehaviour objCreate = new CreateObjectCommand(objToCreate, UniSystems.getInstance());
        
        ICommand command = new Command(objCreate);
        
        UniSystems.getInstance().setLastCommand(objCreate);
        
        return this.objCmdTracker.executeCommand(command);
    }

    
    public Boolean deleteObject(Object objToDelete) {
        ICommandBehaviour objDelete = new DeleteObjectCommand(objToDelete, UniSystems.getInstance());
        
        ICommand command = new Command(objDelete);
        
        UniSystems.getInstance().setLastCommand(objDelete);
        
        return this.objCmdTracker.executeCommand(command);
    }
    
    public Boolean editObject(Object oldObject, Object newObject){
        ICommandBehaviour objEdit = new EditObjectCommand(oldObject, newObject, UniSystems.getInstance());
        
        ICommand command = new Command(objEdit);
        
        UniSystems.getInstance().setLastCommand(objEdit);
        
        return this.objCmdTracker.executeCommand(command);
    }
    
    public void validateInputs(JPanel panel) throws Exception {
        //validate code
        Boolean error = false;
        String errorMessage = "";
        //Object[] inputFields = new Object[5];

        try {
            if (panel == pnlAdministrator){
                if (lstAdministrator.getSelectedIndex() == -1){
                    error = true;
                    errorMessage = "Administrator must be selected from list.";
                }
            } else if (panel == pnlCars){
                if (lstCars.getSelectedIndex() == -1){
                    error = true;
                    errorMessage = "Car must be selected from list.";
                }
            } else if (panel == pnlRentals){
                if (lstRentals.getSelectedIndex() == -1){
                    error = true;
                    errorMessage = "Rental must be selected from list.";
                }
            } else if (panel == pnlReservations){
                if (lstReservations.getSelectedIndex() == -1){
                    error = true;
                    errorMessage = "Reservation must be selected from list.";
                }
            } else if (panel == pnlStaff){
                if (lstStaff.getSelectedIndex() == -1){
                    error = true;
                    errorMessage = "Staff member must be selected from list.";
                }
            }
        } catch (IndexOutOfBoundsException ex) {

        }

        if (error) {
            throw new Exception(errorMessage);
        }
    }
    
    public void setLogin(int login) {
        this.login = login;
    }
    
    public Integer getLogin(){
        return this.login;
    }
    
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnAddAdmin;
    private javax.swing.JButton btnAddCar;
    private javax.swing.JButton btnAddRental;
    private javax.swing.JButton btnAddStaff;
    private javax.swing.JButton btnAdministrator;
    private javax.swing.JButton btnBack;
    private javax.swing.JButton btnBack1;
    private javax.swing.JButton btnBack3;
    private javax.swing.JButton btnBack4;
    private javax.swing.JButton btnBack5;
    private javax.swing.JButton btnCancelReservation;
    private javax.swing.JButton btnCars;
    private javax.swing.JButton btnDeleteAdmin;
    private javax.swing.JButton btnDeleteCar;
    private javax.swing.JButton btnDeleteStaff;
    private javax.swing.JButton btnEditAdmin;
    private javax.swing.JButton btnEditCar;
    private javax.swing.JButton btnEditStaff;
    private javax.swing.JButton btnNewReservation;
    private javax.swing.JButton btnRentals;
    private javax.swing.JButton btnReservations;
    private javax.swing.JButton btnReturnRental;
    private javax.swing.JButton btnReviewRental;
    private javax.swing.JButton btnStaff;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JMenuBar jMenuBar1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JScrollPane jScrollPane3;
    private javax.swing.JScrollPane jScrollPane4;
    private javax.swing.JScrollPane jScrollPane5;
    private javax.swing.JPopupMenu.Separator jSeparator1;
    private javax.swing.JList lstAdministrator;
    private javax.swing.JList lstCars;
    private javax.swing.JList lstRentals;
    private javax.swing.JList lstReservations;
    private javax.swing.JList lstStaff;
    private javax.swing.JMenu mnuEdit;
    private javax.swing.JMenuItem mnuExit;
    private javax.swing.JMenu mnuFile;
    private javax.swing.JMenuItem mnuRedo;
    private javax.swing.JMenuItem mnuSave;
    private javax.swing.JMenuItem mnuUndo;
    private javax.swing.JPanel pnlAdministrator;
    private javax.swing.JPanel pnlCars;
    private javax.swing.JPanel pnlHome;
    private javax.swing.JPanel pnlRentals;
    private javax.swing.JPanel pnlReservations;
    private javax.swing.JPanel pnlStaff;
    // End of variables declaration//GEN-END:variables
}